name: '🔬 CI — Test'

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
    name: Check
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v4

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ➕ Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: 📦 Installing Dependencies
        run: npm ci

      - name: 🧪 Test
        run: npm run test
